
package Vista;

import LogicaNegocio.TemaLN;
import LogicaNegocio.PreguntaLN;
import DTO.PreguntaTema;
import DTO.Tema;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase para que el usuario Administre las respuestas
 *
 * @author Daniel Restrepo Email: danistiven19@gmail.com
 * @author Julian Montoya Email: julianesten@gmail.com
 * @author Luisa Suarez Email: lsuarezzapata5@gmail.com
 */
public class AdministrarRespuestas extends javax.swing.JFrame {

    Tema temaMaestro;
    private TemaLN ctrlTema = new TemaLN();
    private PreguntaLN ctrlPregunta = new PreguntaLN();
    Collection<Tema> temas;

    public AdministrarRespuestas() {
        initComponents();
        setLocationRelativeTo(null);
        temaMaestro = ctrlTema.cargarTema(0);
        Iterator it = temaMaestro.getPreguntas().iterator();
        while (it.hasNext()) {
            PreguntaTema tt = (PreguntaTema) it.next();
            cbPregunta.addItem(tt.getPregunta().getId());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPregResp = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRespuestasDeTemas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbPregunta = new javax.swing.JComboBox();
        cbOpcion = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pregunta:");

        tbPregResp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pregunta", "Respuesta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPregResp);

        btnAgregar.setText("Agregar Respuesta");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Resuestas");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Volver");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Respuesta:");

        btnRespuestasDeTemas.setText("Ver respuestas de todos los temas");
        btnRespuestasDeTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestasDeTemasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese las respuestas del examen maestro:");

        cbPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPreguntaActionPerformed(evt);
            }
        });

        cbOpcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        cbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcionActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRespuestasDeTemas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnRespuestasDeTemas))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        String[] datos = {cbPregunta.getSelectedItem().toString(), cbOpcion.getSelectedItem().toString()};
        dft.addRow(datos);
        tbPregResp.setModel(dft);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        for (int i = 0; i < dft.getRowCount(); i++) {
            Iterator it = temaMaestro.getPreguntas().iterator();
            while (it.hasNext()) {
                PreguntaTema preguntaTema = (PreguntaTema) it.next();
                if (preguntaTema.getPregunta().getId() == Integer.parseInt(dft.getValueAt(i, 0).toString())) {
                    int rta = 0;
                    String letra = dft.getValueAt(i, 1).toString();
                    if (letra.equals("A")) {
                        rta = 1;
                    } else if (letra.equals("B")) {
                        rta = 2;
                    } else if (letra.equals("C")) {
                        rta = 3;
                    } else if (letra.equals("D")) {
                        rta = 4;
                    }
                    preguntaTema.setRespuestaCorrecta(rta);
                }
            }
        }
        ctrlTema.ingresarRespuesta(temaMaestro);
        ctrlTema.desplegarRespuestas(temaMaestro);
        limpiarTabla();
        btnAgregar.setEnabled(false);
        btnGuardar.setEnabled(false);
        cbPregunta.setEnabled(false);
        cbOpcion.setEnabled(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        ExamenesCtrl exa = new ExamenesCtrl();
        exa.abrirPrincipal();
        this.hide();
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnRespuestasDeTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestasDeTemasActionPerformed
        try {
            String nombreArchivo = JOptionPane.showInputDialog("Ingrese el nombre del archivo que contendrá la relacion Tema-Respuestas");
            Desktop.getDesktop().open(ctrlTema.escribirArchivoExcel(nombreArchivo));
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, "Problemas al momento de crear el archivo Tema-Respuestas! Error: " + e);
        }
    }//GEN-LAST:event_btnRespuestasDeTemasActionPerformed

    private void cbPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPreguntaActionPerformed

    }//GEN-LAST:event_cbPreguntaActionPerformed

    private void cbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcionActionPerformed

    }//GEN-LAST:event_cbOpcionActionPerformed

    private void actualizarTabla(Tema tt) {
        if (tt.getPreguntas() != null) {
            DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
            limpiarTabla();
            Iterator it = tt.getPreguntas().iterator();
            while (it.hasNext()) {
                PreguntaTema preguntaTema = (PreguntaTema) it.next();
                int rta = preguntaTema.getRespuestaCorrecta();
                String letra = "";
                if (rta == 1) {
                    letra = "A";
                } else if (rta == 2) {
                    letra = "B";
                } else if (rta == 3) {
                    letra = "C";
                } else if (rta == 4) {
                    letra = "D";
                }

                String[] datos = {Integer.toString(preguntaTema.getNumeroPregunta()), letra};
                dft.addRow(datos);
            }
            tbPregResp.setModel(dft);
        }
    }

    public void limpiarTabla() {
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        while (dft.getRowCount() > 0) {
            dft.removeRow(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarRespuestas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRespuestasDeTemas;
    private javax.swing.JComboBox cbOpcion;
    private javax.swing.JComboBox cbPregunta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPregResp;
    // End of variables declaration//GEN-END:variables
}
