package Vista;

import LogicaNegocio.OpcionLN;
import LogicaNegocio.PreguntaLN;
import LogicaNegocio.LatexLN;
import LogicaNegocio.ArchivoLN;
import DTO.Opcion;
import DTO.Pregunta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Clase para que el usuario Administre las opciones
 *
 * @author Daniel Restrepo Email: danistiven19@gmail.com
 * @author Julian Montoya Email: julianesten@gmail.com
 * @author Luisa Suarez Email: lsuarezzapata5@gmail.com
 */
public class AdministrarOpcion extends javax.swing.JFrame {

    private Opcion opcion;
    String descripcionOpcion;
    ArrayList opciones;
    int seleccion;
    private PreguntaLN preguntaLn = new PreguntaLN();
    private OpcionLN opcionLn = new OpcionLN();

    public AdministrarOpcion(Opcion opcion1, int sel) {
        initComponents();
        setLocationRelativeTo(null);
        ArchivoLN archivoLn = new ArchivoLN();
        this.opcion = opcion1;
        this.seleccion = sel;
        opciones = new ArrayList();
        preguntaLn.listarOpcionesDePRegunta(opcion1.getPregunta());
        opciones = (ArrayList) preguntaLn.listarOpcionesDePRegunta(opcion1.getPregunta());

        DefaultComboBoxModel listaOpciones = (DefaultComboBoxModel) cb_DespuesDeOpcion.getModel();
        listaOpciones.addElement("Ninguno");
        Iterator j = opciones.iterator();
        while (j.hasNext()) {
            Opcion op = (Opcion) j.next();
            if (opcion1.getId() != op.getId()) {
                listaOpciones.addElement(op.getId());
            }
        }

        cb_DespuesDeOpcion.setModel(listaOpciones);
        if (sel == 1) {
            txt_DescripcionOpcion.setText(opcion1.getDescripcion());
            if (opcion1.getDespuesDe().getId() != 0) {
                cb_DespuesDeOpcion.setSelectedIndex(opcion1.getDespuesDe().getId() - 1);

            } else {
                cb_DespuesDeOpcion.setSelectedItem("Ninguno");
            }

            cb_OrdenOpcion.setSelectedIndex(opcion1.getOrden() - 1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DescripcionOpcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cb_OrdenOpcion = new javax.swing.JComboBox();
        btn_volver = new javax.swing.JButton();
        cb_DespuesDeOpcion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        btn_SeleccionarImagen = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Opción");

        txt_DescripcionOpcion.setColumns(20);
        txt_DescripcionOpcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DescripcionOpcion.setRows(5);
        jScrollPane1.setViewportView(txt_DescripcionOpcion);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Orden");

        cb_OrdenOpcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_OrdenOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Primero", "Ultimo" }));
        cb_OrdenOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_OrdenOpcionActionPerformed(evt);
            }
        });

        btn_volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        cb_DespuesDeOpcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Despues de");

        btn_Guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_SeleccionarImagen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_SeleccionarImagen.setText("Seleccionar imagen");
        btn_SeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarImagenActionPerformed(evt);
            }
        });

        lblInformacion.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_SeleccionarImagen))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(336, 336, 336)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cb_OrdenOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_DespuesDeOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SeleccionarImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_OrdenOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_DespuesDeOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Guardar))
                .addGap(18, 18, 18)
                .addComponent(lblInformacion)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Pregunta pregunta = new Pregunta();
        pregunta.setId(opcion.getPregunta().getId());
        preguntaLn.cargarInfPreg(pregunta);
        ExamenesCtrl ex = new ExamenesCtrl();
        ex.abrirPregunta(pregunta, 1);
        this.hide();

    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        Pregunta pregunta = new Pregunta();
        pregunta = opcion.getPregunta();
        if (txt_DescripcionOpcion.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la descripción");
            txt_DescripcionOpcion.requestFocus();
            return;
        }
        String textoEnunciado = txt_DescripcionOpcion.getText();
        char comillaSimple = 39;
        char comillaDoble = 34;
        String nuevoTexto = textoEnunciado.replace(comillaSimple, comillaDoble);
        txt_DescripcionOpcion.setText(nuevoTexto);

        opcion.setDescripcion(txt_DescripcionOpcion.getText());
        Opcion op2 = new Opcion();
        if (cb_DespuesDeOpcion.getSelectedItem() == "Ninguno") {
            op2.setId(0);
        } else {
            if (cb_OrdenOpcion.getSelectedIndex() != 0) {
                JOptionPane.showMessageDialog(this, "Verifique sus condiciones, no pueden ingresar dos condicionamientos diferentes");
                return;
            }
            op2.setId(Integer.parseInt(cb_DespuesDeOpcion.getSelectedItem().toString()));
        }
        opcion.setDespuesDe(op2);
        opcion.setOrden(cb_OrdenOpcion.getSelectedIndex() + 1);
        LatexLN lt = new LatexLN();
        try {
            if (lt.crearOpcion(opcion) == 1) {
                ExamenesCtrl exa = new ExamenesCtrl();
                if (seleccion == 2) {
                    if (opcionLn.crearOpcion(opcion) == 1) {
                        //Duplicar ls backSlashh!
                        lblInformacion.setText("Opcion " + opcion.getId() + " almacenada correctamente!");
                        exa.abrirPregunta(opcion.getPregunta(), 1);
                        this.hide();
                    }

                } else {
                    if (opcionLn.modificarOpcion(opcion) == 1) {
                        lblInformacion.setText("Opcion " + opcion.getId() + " modificada correctamente!");
                        exa.abrirPregunta(opcion.getPregunta(), 1);
                        this.hide();
                    }
                }
            }
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(AdministrarEnunciado.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void cb_OrdenOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_OrdenOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_OrdenOpcionActionPerformed

    private void btn_SeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarImagenActionPerformed
        JFileChooser elegir = new JFileChooser();
        int idOpcion = elegir.showOpenDialog(btn_SeleccionarImagen);

        if (idOpcion == JFileChooser.APPROVE_OPTION) {
            String pathArchivo = elegir.getSelectedFile().getPath(); //Obtiene path del archivo
            String nombre = elegir.getSelectedFile().getName(); //obtiene nombre del archivo
            String path = pathArchivo.replace('\\', '/');
            txt_DescripcionOpcion.insert("\\includegraphics{" + path + "}", txt_DescripcionOpcion.getCaretPosition());

        }
    }//GEN-LAST:event_btn_SeleccionarImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarOpcion(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_SeleccionarImagen;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox cb_DespuesDeOpcion;
    private javax.swing.JComboBox cb_OrdenOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JTextArea txt_DescripcionOpcion;
    // End of variables declaration//GEN-END:variables
}
