package Vista;

import DTO.Tema;
import LogicaNegocio.LatexLN;
import LogicaNegocio.TemaLN;
import java.io.IOException;
import java.util.Collection;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Clase para que el usuario Administre la aplicacion
 *
 * @author Daniel Restrepo Email: danistiven19@gmail.com
 * @author Julian Montoya Email: julianesten@gmail.com
 * @author Luisa Suarez Email: lsuarezzapata5@gmail.com
 */
public class Principal extends javax.swing.JFrame {

    ExamenesCtrl ex = new ExamenesCtrl();

    Collection<Tema> temas;
    public TemaLN temaLn = new TemaLN();

    public Principal() {
        initComponents();
        actualizar();
        setLocationRelativeTo(null);

    }

    public void actualizar() {
        temas = temaLn.listarTemas();
        cbTema.removeAllItems();
        Iterator it = temas.iterator();
        while (it.hasNext()) {
            Tema tt = (Tema) it.next();
            cbTema.addItem(tt.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministrarEnunciado = new javax.swing.JButton();
        btnGenerarMaestro = new javax.swing.JButton();
        btnGenerarTemas = new javax.swing.JButton();
        btnIngresarRespuestas = new javax.swing.JButton();
        btnIngresarCredenciales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        cbTema = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnAdministrarEnunciado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdministrarEnunciado.setText("Administrar Enunciado");
        btnAdministrarEnunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarEnunciadoActionPerformed(evt);
            }
        });

        btnGenerarMaestro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerarMaestro.setText("Generar Maestro");
        btnGenerarMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMaestroActionPerformed(evt);
            }
        });

        btnGenerarTemas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerarTemas.setText("Generar Temas");
        btnGenerarTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTemasActionPerformed(evt);
            }
        });

        btnIngresarRespuestas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresarRespuestas.setText("Administrar Respuestas");
        btnIngresarRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarRespuestasActionPerformed(evt);
            }
        });

        btnIngresarCredenciales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresarCredenciales.setText("Ingresar Credenciales");
        btnIngresarCredenciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCredencialesActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escudo.jpg"))); // NOI18N

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnImprimir.setText("Imprimir Tema");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        cbTema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGenerarMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarRespuestas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarCredenciales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbTema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdministrarEnunciado, btnGenerarMaestro, btnGenerarTemas, btnIngresarCredenciales, btnIngresarRespuestas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdministrarEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarMaestro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarTemas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(cbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresarCredenciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresarRespuestas)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarEnunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarEnunciadoActionPerformed
        ex.abrirAdminEnunciados();
        this.hide();
    }//GEN-LAST:event_btnAdministrarEnunciadoActionPerformed

    private void btnGenerarMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMaestroActionPerformed
        ex.abrirInformacionExamen();
        this.hide();
    }//GEN-LAST:event_btnGenerarMaestroActionPerformed

    private void btnGenerarTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTemasActionPerformed
        LatexLN latexLn = new LatexLN();
        for (int i = 0; i < 10; i++) {
            temaLn.hacerRandom();
        }
        actualizar();
    }//GEN-LAST:event_btnGenerarTemasActionPerformed

    private void btnIngresarRespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarRespuestasActionPerformed
        ExamenesCtrl exa = new ExamenesCtrl();
        exa.abrirRespuestas();
        this.hide();
    }//GEN-LAST:event_btnIngresarRespuestasActionPerformed

    private void btnIngresarCredencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCredencialesActionPerformed
        ExamenesCtrl exa = new ExamenesCtrl();
        exa.abrirCredenciales();
        this.hide();
    }//GEN-LAST:event_btnIngresarCredencialesActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            Tema t = temaLn.cargarTema(Integer.parseInt(cbTema.getSelectedItem().toString()));
            t.setJornada("Mañana");
            temaLn.imprimir(t);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarEnunciado;
    private javax.swing.JButton btnGenerarMaestro;
    private javax.swing.JButton btnGenerarTemas;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIngresarCredenciales;
    private javax.swing.JButton btnIngresarRespuestas;
    private javax.swing.JComboBox cbTema;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
